# EP.02 card definitions: (file, org, meta, tag, body_html, source). Court rulings and official announcements only.
# Officials are identified by position only (per rulings). Cho Hee-pal was never tried; nothing here states his guilt as a court finding.
CARDS = [
 ("card_01_scale_70000_victims", "PROSECUTORS / SUPREME COURT OF KOREA", "THE CHO HEE-PAL CASE · 2004–2008", "THE SCALE",
  "About <mark>70,000 victims</mark>.<br>About <mark>5.07 trillion won</mark> taken in.",
  "Source: prosecutors' announcement (June 28, 2016); Supreme Court ruling in the Kang Tae-yong case (Nov 29, 2017), as reported by Seoul Shinmun and Edaily"),
 ("card_02_the_promise_35000_won", "DAEGU DISTRICT COURT", "RULING IN THE KANG TAE-YONG CASE · JANUARY 13, 2017", "THE PROMISE",
  "Buy a device for <mark>4.4 million won</mark>. Get <mark>35,000 won</mark> every business day. The court described it as a fixed return of <mark>35% a year</mark>.",
  "Sources: Daegu District Court ruling (Jan 13, 2017), as reported by Seoul Shinmun; SisaIN, December 2008"),
 ("card_03_superintendent_900m_won", "SUPREME COURT OF KOREA", "BRIBERY RULING · DECEMBER 2016", "RULING",
  "A former senior police officer received <mark>900 million won in cashier's checks</mark> from Cho at a Daegu hotel coffee shop on <mark>October 30, 2008</mark>.<br>Sentence: <mark>9 years</mark>.",
  "Former superintendent, Daegu police. Sources: Hankook Ilbo (Dec 18, 2016); Edaily; Seoul Shinmun"),
 ("card_04_prosecution_official_9_years", "SUPREME COURT OF KOREA", "BRIBERY RULING · OCTOBER 2016", "RULING",
  "A former official at the Daegu prosecutors' office took bribes from <mark>2008 to 2013</mark>, mostly from a man managing the group's hidden money.<br>Sentence: <mark>9 years</mark> and a <mark>1.4 billion won</mark> fine.",
  "Sources: Hankook Ilbo (Oct 16, 2016); Edaily"),
 ("card_05_sergeant_district_court", "DAEGU DISTRICT COURT", "BRIBERY RULING · SEPTEMBER 30, 2016", "DISTRICT COURT RULING",
  "A former police sergeant who investigated the case took bribes, and the court found he <mark>prolonged the investigation</mark>.<br>Sentence: <mark>8 years</mark>.",
  "First-instance ruling. Sources: Edaily; Seoul Shinmun"),
 ("card_06_police_death_announcement", "KOREAN POLICE", "ANNOUNCEMENT · MAY 21, 2012", "OFFICIAL ANNOUNCEMENT",
  "Police said Cho died of <mark>acute myocardial infarction</mark> in China in <mark>December 2011</mark>.<br>He was kept on the <mark>wanted list</mark>.",
  "Sources: Seoul Shinmun (May 21, 2012); Maeil Shinmun (May 22, 2012); Seoul Shinmun (Oct 13, 2015)"),
 ("card_07_prosecutors_conclusion", "DAEGU DISTRICT PROSECUTORS' OFFICE", "CONCLUSION · JUNE 28, 2016", "OFFICIAL CONCLUSION",
  "Prosecutors concluded Cho died around <mark>December 19, 2011</mark>, in <mark>Weihai, China</mark>, and closed his case with <mark>“no right of prosecution.”</mark>",
  "Sources: Hankook Ilbo, Maeil Shinmun, Seoul Shinmun, Kookmin Ilbo (June 28, 2016)"),
 ("card_08_kang_tae_yong_22_years", "SUPREME COURT OF KOREA", "THE KANG TAE-YONG CASE · NOVEMBER 29, 2017", "FINAL RULING",
  "Cho's right-hand man, <mark>Kang Tae-yong</mark>, was sentenced to <mark>22 years in prison</mark> for fraud, embezzlement and bribery.",
  "Sources: Seoul Shinmun (Jan 13, Aug 10 and Nov 29, 2017); Edaily"),
 ("card_09_payout_2026", "DAEGU DISTRICT COURT, WESTERN BRANCH", "DISTRIBUTION · JUNE 24, 2026", "18 YEARS LATER",
  "<mark>32 billion won</mark> to be paid out to <mark>22,156 creditors</mark>.",
  "Source: Hankyung (June 24, 2026)"),
 ("card_10_fss_2024_reports", "FINANCIAL SUPERVISORY SERVICE (KOREA)", "PRESS RELEASE · FEBRUARY 11, 2025", "IT KEEPS COMING BACK",
  "Reports of illegal fund-raising schemes in 2024: <mark>410</mark>, up <mark>25%</mark> from the year before.",
  "Source: FSS press release (Feb 11, 2025), via KDI Economic Information Center"),
]
